baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"

title = "My New Hugo Site"
themesdir = "../../"
theme = "hugo-theme-misidoc"


[languages]
  [languages.en]
  # contentDir = 'content/en'
  languageName = 'English'
  weight = 10

  [languages.zh-hans]
  # contentDir = 'content/zh-hans'
  languageName = '简体中文'
  weight = 20


  [[languages.en.menu.main]]
  name = "Posts"
  url = "/posts"
  weight = "2"
  [[languages.en.menu.main]]
  name = "News"
  url = "/news"
  weight = "3"

  [[languages.zh-hans.menu.main]]
  name = "博文"
  url = "/posts"
  weight = "2"
  [[languages.zh-hans.menu.main]]
  name = "新闻"
  url = "/news"
  weight = "3"


# Hugo 解析文档的配置
[markup]
  # 语法高亮设置
  [markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = true
  noClasses = false
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
    [markup.goldmark.renderer]
    # 是否在文档中直接使用 HTML 标签
    unsafe = true

# 目录设置
[markup.tableOfContents]
endLevel = 6
startLevel = 2
